version: "3.8"

services:
  app:
    image: request-count:1.0.0
    environment:
      - PORT=8083
      - REDIS_HOST=redis:6379
      - REDIS_DB=0
    ports:
      - "8083:8083"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:8083/health || exit 1"
    deploy:
      replicas: 3

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
